export enum ACTIONS {
    SET_IS_OPEN_HEADER = "SET_IS_OPEN_HEADER",

    SET_LOGIN_FORM_EMAIL = "SET_LOGIN_FORM_EMAIL",
    SET_LOGIN_FORM_PASSWORD = "SET_LOGIN_FORM_PASSWORD",

    SET_REGISTRATION_FORM_EMAIL = "SET_REGISTRATION_FORM_EMAIL",
    SET_REGISTRATION_FORM_USERNAME = "SET_REGISTRATION_FORM_USERNAME",
    SET_REGISTRATION_FORM_PASSWORD = "SET_REGISTRATION_FORM_PASSWORD",
    SET_REGISTRATION_FORM_CONFIRM_PASSWORD = "SET_REGISTRATION_FORM_CONFIRM_PASSWORD",
}