export { Header } from "./Header/Header"
export { LoginForm } from "./LoginForm/LoginForm"
export { NewPasswordForm } from "./NewPasswordForm/NewPasswordForm"
export { PostCards } from "./PostCards/PostCards"
export { RegistrationForm } from "./RegistrationForm/RegistrationForm"
export { ResetPasswordForm } from "./ResetPasswordForm/ResetPasswordForm"